language: node_js
node_js:
  - 6

cache:
  directories:
    - node_modules

after_success: npm run coverage

# for nightmarejs
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
